### ISSUE TITLE
Fix CNAME

### ISSUE THREAD

**Issue by nelsonjchen** [desertpy/desertpy-pelican#16]
https://github.com/desertpy/desertpy-pelican/settings

Search page for "Custom domains". Add desertpy.com

**Comment by nelsonjchen** [comment]
Also, we might as well go enforce HTTPS.

**Comment by godber** [comment]
I've updated DNS to support http, it will take a while to propagate.

**Comment by godber** [comment]
Oh, and set the custom domain in the settings.

**Comment by nelsonjchen** [comment]
😒

We'll need to restore that CNAME file copying. The interface adds a `CNAME` file which then gets blown away on the next deploy. 

https://github.com/mkdocs/mkdocs/issues/1496#issue-326336038
