### ISSUE TITLE
Create a lighting talk page

### ISSUE THREAD

**Issue by godber** [desertpy/desertpy-pelican#4]
This page should maintain a running list of recommended lighting talk suggestions that people can pluck from.  We can cross out topics that have been addressed.

**Comment by aganders3** [comment]
Is there a way to make a wiki-style page for this in Pelican, or do you just anticipate adding things yourself? I'm happy to make a skeleton for the page, but it would be nice to have a list to start with.

**Comment by godber** [comment]
The desertpy site is entirely static, thats what pelican generates.  I was anticipating that we would create a master list of some sort and then we'd manually strikethrough the ones that get completed.

I've had requests for newbie material, which I thought we might make a point to regularly integrate some newbie stuff, perhaps in the form of lightning talks.

I just had an idea which I just tested out ... one can embed gists in webpages, this might simplify the task of keeping the list up to date ... all I have to do to mark something off is to go to the gist and check the box.

See this gist:

https://gist.github.com/godber/be7b6e6b0e55d4db2563

embedded here:

http://molokai.sese.asu.edu/~godber/g.html

**Comment by aganders3** [comment]
Wow, that works really well actually and even takes on some of the fonts/styling of the surrounding page. It makes sense to limit access to prevent any potential vandalism as well. I'll create a pull request for the page, and a starting list in a gist.
